### ISSUE TITLE
Unable to find 'conquer \ i18n \ controllers \ DefaultController' in file. Namespace missing?

### ISSUE THREAD

**Issue by obladon25** [borodulin/yii2-i18n-google#1]
Hello.
I use Yii2 Basic.
I installed the extension, on sait on localhost, I set all in config The options under instruction. But I error occurs:
"
Unknown Class - Yii \ base \ UnknownClassException
Unable to find 'conquer \ i18n \ controllers \ DefaultController' in file: /var/www/html/vendor/conquer/i18n/controllers/DefaultController.php. Namespace missing?
"
the file structure "DefaultController.php" is just this:
"" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "
<? Php
/ **
 \* @link Https://github.com/borodulin/yii2-i18n-google
 \* @copyright Copyright (c) 2015 Andrey Borodulin
 \* @license Https://github.com/borodulin/yii2-i18n-google/blob/master/LICENSE
 \* /

namespace conquer \ i18n \ controllers;
"" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
I'm new to Yii2. and I can not clarify the contents of the file must be another? I drew attention in files on GitHub, directory controller are 3 files to me only "DefaultController.php".
Thank you

**Comment by borodulin** [comment]
Hi! This extension does not make sense because there is an easier way to connect the machine translation. I was trying to make a story, if you wish, you can help me make a clear description. https://github.com/borodulin/yii2-cookbook/blob/master/book/i18n-using-yandex-as-translation-source.md
With regards to this extension, I want to remove it in the near future ... I have long come to the conclusion that the supply CRUD with the components - not productive.
Instead these controllers you should make your own through the CRUD generator.
